import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/page/Hero'
import Demo from '../components/page/Demo'
import Services from '../components/page/Services'
import Portfolio from '../components/page/Portfolio'
import Contact from '../components/page/Contact'
import Footer from '../components/Footer'
import styles from '../styles/Index.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Enver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./Images/Logo Icon 1.svg" />
      </Head>

      <main>
        <Hero/>
        <Demo/>
        <Services/>
        <Portfolio/>
        <Contact/>
        <Footer/>
      </main>

    </div>
  )
}
